name: bladedefect
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - pyyaml
  - matplotlib
  - pillow
  - tqdm
  - opencv
  - pytest
  - pip:
      - ultralytics
      - streamlit
      - gradio
      - rich
