# 修改为实际数据集根目录；可使用绝对路径或相对此文件的路径。
path: ../datasets/blade-small
train: images/train
val: images/val
test: images/test

names:
  0: 表面腐蚀--保护膜损伤
  1: 表面腐蚀--玻纤腐蚀
  2: 表面腐蚀--合模缝裸漏
  3: 表面腐蚀--胶衣腐蚀
  4: 表面裂纹--玻纤裂纹
  5: 表面裂纹--后缘弦向裂纹
  6: 表面缺陷--表面掉漆
  7: 表面缺陷--表面油污
  8: 表面缺陷--胶衣脱落
  9: 表面缺陷--胶衣裂纹
  10: 维修痕迹
  11: 叶片损伤--玻纤损伤
  12: 叶片损伤--叶片开裂
  13: 叶片损伤--结构损伤
  14: 附件脱落--接闪器脱落
